### ISSUE TITLE
Horrendously Unstable

### ISSUE THREAD

**Issue by LivacoNew** [cepheidqq/FactorySkyline#58]
Like 4 issues to report here...

- Keybind settings don't save across restarts.
- Blueprint's don't save across restarts.
- Highlighting for blueprints crashes my game
- Flying doesn't work
- When mass disassembling without using the mod, cursor will appear causing me to not be able to move my camera. This only happens with this mod installed.

I refuse to believe this is supported for U5, because half of this should be caught instantly.

**Comment by zoqin** [comment]
I love the mod but I have similar issues
- I can fly but I experience heavy stutter
- Sometime when I highlight blueprints, game crash
- There is some power cable impossible to select

I know this is this mod as this is the only mod I installed since I experience crash

For me keybind and blueprints save as long the game was save, maybe you crash sometime before save ?
Do you have over mod that enable flying ? maybe they are canceling each other
You can change you keybind to not trigger the cursor so you don't have disassembling issue, the cursor keybind is call "control" if i remember correctly, I have bind it to ctrl + c for example
